<?xml version="1.0"?>

<robot xmlns:xacro="https://www.ros.org/wiki/xacro">

    <xacro:property name="arm_base_length" value="0.1"></xacro:property>
    <xacro:property name="arm_base_width" value="0.1"></xacro:property>
    <xacro:property name="arm_base_height" value="0.02"></xacro:property>
    <xacro:property name="forearm_radius" value="0.02"></xacro:property>
    <xacro:property name="forearm_length" value="0.3"></xacro:property>
    <xacro:property name="hand_radius" value="0.02"></xacro:property>
    <xacro:property name="hand_length" value="0.3"></xacro:property>

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"></box>
            </geometry>
            <origin xyz="0 0 ${arm_base_height / 2.0}" rpy="0 0 0"></origin>
            <material name="orange"></material>
        </visual>

    </link>   
    
    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}"></cylinder>
            </geometry>
            <origin xyz="0 0 ${forearm_length / 2.0}" rpy="0 0 0"></origin>
            <material name="yellow"></material>
        </visual>
    </link>

    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}"></cylinder>
            </geometry>
            <origin xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0"></origin>
            <material name="orange"></material>
        </visual>
    </link>

    <joint name="arm_base_forearm_joint" type="revolute">
        <parent link="arm_base_link"></parent>
        <child link="forearm_link"></child>
        <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0"></origin>
        <axis xyz="0 1 0"></axis>
        <limit lower="0" upper="${pi / 2.0}" effort="100" velocity="100"></limit>
    </joint>

    <joint name="forearm_hand_joint" type="revolute">
        <parent link="forearm_link"></parent>
        <child link="hand_link"></child>
        <origin xyz="0 0 ${forearm_length}" rpy="0 0 0"></origin>
        <axis xyz="0 1 0"></axis>
        <limit lower="0" upper="${pi / 2.0}" effort="100" velocity="100"></limit>
    </joint>

</robot>