<?xml version="1.0"?>

<robot xmlns:xacro="https://www.ros.org/wiki/xacro">

    <xacro:property name="camera_length" value="0.01"></xacro:property>
    <xacro:property name="camera_width" value="0.1"></xacro:property>
    <xacro:property name="camera_height" value="0.05"></xacro:property>

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"></box>
            </geometry>
            <material name="grey"></material>
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"></box>
            </geometry>
        </collision>
        <xacro:box_inertia m="0.1" x="${camera_length}" y="${camera_width}" z="${camera_height}" o_xyz="0 0 0" o_rpy="0 0 0"></xacro:box_inertia>
    </link>

    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link"></parent>
        <child link="camera_link"></child>
        <origin xyz="${(base_length + camera_length)/ 2.0  } 0 ${base_height / 2.0}" rpy="0 0 0"></origin>
    </joint>

</robot>