<?xml version="1.0"?>

<robot xmlns:xacro="https://www.ros.org/wiki/xacro" >
    
    <xacro:property name="base_length" value="0.6"></xacro:property>
    <xacro:property name="base_width" value="0.4"></xacro:property>
    <xacro:property name="base_height" value="0.2"></xacro:property>
    <xacro:property name="wheel_radius" value="0.1"></xacro:property>
    <xacro:property name="wheel_length" value="0.05"></xacro:property>

    <link name="base_footprint"></link>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"></box>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"></origin>
            <material name="violet"></material>
        </visual>
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"></cylinder>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"></origin>
                <material name="grey"></material>
            </visual>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right"></xacro:wheel_link>
    <xacro:wheel_link prefix="left"></xacro:wheel_link>

    <link name="castor_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius/2.0}"></sphere>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"></origin>
            <material name="grey"></material>
        </visual>
    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"></parent>
        <child link="base_link"></child>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"></origin>
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link"></parent>
        <child link="right_wheel_link"></child>
        <origin xyz="${-base_length / 4.00} ${-(base_width + wheel_length) / 2} 0" rpy="0 0 0"></origin>
        <axis xyz="0 1 0"></axis>
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link"></parent>
        <child link="left_wheel_link"></child>
        <origin xyz="${-base_length / 4.00} ${(base_width + wheel_length) / 2 } 0" rpy="0 0 0"></origin>
        <axis xyz="0 1 0"></axis>
    </joint>

    <joint name="base_castor_wheel_joint" type="continuous">
        <parent link="base_link"></parent>
        <child link="castor_wheel_link"></child>
        <origin xyz="${base_length / 3.00} 0 ${-(wheel_radius/2)}" rpy="0 0 0"></origin>
    </joint>
</robot>