<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="https://www.ros.org/wiki/xacro">
   
    <xacro:include  filename="common_properties.xacro"></xacro:include>
    <xacro:include  filename="mobile_base.xacro"></xacro:include>
    <xacro:include  filename="mobile_base_gazebo.xacro"></xacro:include>
    <xacro:include  filename="camera.xacro"></xacro:include>

    <xacro:include  filename="arm.xacro"></xacro:include>
    <xacro:include  filename="arm_gazebo.xacro"></xacro:include>

    <joint name="mobile_base_arm_joint" type="fixed">
        <parent link="base_link"></parent>
        <child link="arm_base_link"></child>
        <origin xyz="${base_length / 4.0} 0 ${base_height}" rpy="0 0 0"></origin>
    </joint> 
</robot>